apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfolio-deployment
  labels:
    app: devops-portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-portfolio
  template:
    metadata:
      labels:
        app: devops-portfolio
      annotations:
        eks.amazonaws.com/fargate-profile: default
    spec:
      containers:
      - name: devops-portfolio
        image: manukrishnayadav/my-devops-portfolio:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"